import { Box, Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { PageContainer } from "../../src/global/PageContainer";
import { projectMetaData } from "../../src/projects/database/ProjectMetaData";
import { ProjectItem } from "../../src/projects/components/project-item/ProjectItem";

const Projects: NextPage = () => {
  // Todo: Temporary fix for react-material-ui-carousel not resizing properly on initial page load
  setTimeout(() => {}, 500);

  return (
    <div>
      <Head>
        <title>Projects - Franklin V Moon</title>
        <meta name="projects" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        {projectMetaData.map((dataItem) => {
          return (
            <div key={dataItem.title} style={{ position: "relative" }}>
              <ProjectItem metaData={dataItem} />
            </div>
          );
        })}
      </PageContainer>
    </div>
  );
};

export default Projects;
