import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { PageContainer } from "../../src/global/PageContainer";
import { projectMetaData } from "../../src/projects/database/ProjectMetaData";
import { ProjectItem } from "../../src/projects/ProjectItem";

const Projects: NextPage = () => {
  
  
  
  return (
    <div>
      <Head>
        <title>Projects - Franklin V Moon</title>
        <meta name="projects" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
          {projectMetaData.map((dataItem) => {
            return (
                  <ProjectItem metaData={dataItem} key={dataItem.title}/>
            );
          })}
      </PageContainer>
    </div>
  );
};

export default Projects;
