import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

const Projects: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Projects page</h1>
    </div>
  );
};

export default Projects;
