import type { NextPage } from "next";
import Head from "next/head";
import { PageContainer } from "../../src/global/PageContainer";
import { Languages } from "../../src/skills/Languages";

export const Skills: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Skills - Franklin V Moon</title>
				<meta name='Skills' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<PageContainer>
				<Languages />
			</PageContainer>
		</div>
	);
};

export default Skills;
