import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

export const Skills: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Skills page</h1>
    </div>
  );
};
