import { Languages, Tags, Topic, TutorialMetaData } from "../types";

// TODO: Create a tool to automatically add to this and push it to the github repo
export const tutorialMetaData: TutorialMetaData[] = [
  {
    title: "Dockerize Your Repository",
    link: `dockerize-your-repo`,
    notionPage: "c4ca92237cc4434cbc30119b104e9e87",
    created: 1639982643,
    thumbnail: "/tutorials/dockerize.png",
    subTitle: "Understand and build containers that run your app anywhere",
    topic: Topic.Infrastructure,
    languages: [Languages.Docker],
    tags: [Tags.StepByStep],
  },
  {
    title: "Terminal Commands Cheat Sheet",
    link: `command-cheat-sheet`,
    notionPage: "ea55e3b6a5f54b50abdc456bedc4b80a",
    created: 1639982642,
    thumbnail: "/tutorials/terminal.png",
    subTitle: "List of common commands you'll actually use",
    topic: Topic.Programming,
    languages: [],
    tags: [],
  },
  {
    title: "Deploy Containers to AWS with Terraform",
    link: `deploy-to-aws-ec2-using-terraform-and-docker`,
    notionPage: "4d5154f6347a46d280c19f2d8ad9de4f",
    created: 1639982641,
    thumbnail: "/tutorials/aws-docker-terraform.png",
    subTitle:
      "Step-by-step instructions to spin up AWS and host your project using Terraform",
    topic: Topic.Infrastructure,
    languages: [Languages.Docker, Languages.Terraform],
    tags: [Tags.StepByStep],
  },
  {
    title: "Quickstart: NextJS",
    link: `quickly-setup-next-js-with-typescript`,
    notionPage: "eb6acd5b26d3416c9372be89cae2b05d",
    created: 1639982640,
    thumbnail: "/tutorials/quickstart-next.png",
    subTitle:
      "Get up-and-running with a cleaned up but ready to go NextJs app",
    topic: Topic.Programming,
    languages: [Languages.Typescript, Languages.Javascript],
    tags: [Tags.QuickStart],
  },
  {
    title: "Snippet: Test a Thrown Error",
    link: `test-thrown-error`,
    notionPage: "1ad3c64947224e5e9acf4a09e9086a5b",
    created: 1639982639,
    thumbnail: "/tutorials/test-thrown-error.png",
    subTitle: "Easiest way to test your thrown errors are behaving correctly",
    topic: Topic.Programming,
    languages: [Languages.Typescript, Languages.Javascript],
    tags: [Tags.CodeBlock],
  },
  {
    title: "Override Props for UI Tests",
    link: `override-props-for-ui-tests`,
    notionPage: "c5923b0c20964128be7178d42d7e884b",
    created: 1639982638,
    thumbnail: "/tutorials/override-test-props.png",
    subTitle: "Using a single source for test data and changing only whats needed.",
    topic: Topic.Programming,
    languages: [Languages.Typescript, Languages.Javascript],
    tags: [Tags.StepByStep],
  },
  {
    title: "Snippet: Repeat One Test with New Variables",
    link: `repeat-test-with-new-variables`,
    notionPage: "f5255703bba04229aafded995e423d25",
    created: 1639982637,
    thumbnail: "/tutorials/repeat-test.jpg",
    subTitle: "Using it.each you can pass new values, to test various combinations of inputs and outputs",
    topic: Topic.Programming,
    languages: [Languages.Typescript, Languages.Javascript],
    tags: [Tags.CodeBlock],
  },
  {
    title: "Project Wall: Single Source of Truth",
    link: `project-wall-single-source-of-truth`,
    notionPage: "a036e1f8f1d844a5a512dc6d7a011ccf",
    created: 1639982636,
    thumbnail: "/tutorials/project-wall.jpg",
    subTitle: "Increase distributed team collaboration with a virtual wall",
    topic: Topic.Agile,
    tags: [Tags.Essay],
  },
  {
    title: "Snippet: Create Array with Only Truthy Values",
    link: `filter-array-with-only-truthy-values`,
    notionPage: "f546bb620f29415ba0d9b3b6e5bac748",
    created: 1639982635,
    thumbnail: "/tutorials/array-filter.png",
    subTitle: "Generate an array of values but only include ones that exists, excluding undefined",
    topic: Topic.Programming,
    languages: [Languages.Javascript],
    tags: [Tags.CodeBlock],
  },
  {
    title: "Snippet: Retry Any Function Recursively",
    link: `retry-recursively`,
    notionPage: "88e2d51cb8d74f9a9eb561185f16d322",
    created: 1639982634,
    thumbnail: "/tutorials/retry-recursively.jpg",
    subTitle: "Rerun Function n number of times or handle a thrown error",
    topic: Topic.Programming,
    languages: [Languages.Typescript],
    tags: [Tags.CodeBlock],
  },
  {
    title: "Snippet: Run GraphQL and Express Together",
    link: `run-graphql-and-express`,
    notionPage: "0e6becfb9fb64c6b96f4ef66742ac3e9",
    created: 1639982633,
    thumbnail: "/tutorials/graphql-express.png",
    subTitle: "Easily run two separate backend apis in the same shared code base",
    topic: Topic.Programming,
    languages: [Languages.Typescript],
    tags: [Tags.CodeBlock],
  },
  {
    title: "Snippet: Catch Error By Type",
    link: "try-catch-by-type",
    notionPage: "898854cc62d84573807f8da823304ea0",
    created: 1639982632,
    thumbnail: "/tutorials/try-catch.png",
    subTitle:
      "Handle showing an error to your backend or UI via a simple try/catch",
    topic: Topic.Programming,
    languages: [Languages.Typescript],
    tags: [Tags.CodeBlock],
  }
];
