import { AssetCollectionMetaData } from "../assets/types";

export const stockFootageMetaData: AssetCollectionMetaData[] = [
	{
		title: "Afghanistan",
		thumbnail: "afghanmain.jpg",
		hostedLink: "afghanistan",
		wallpapers: [
			"afghanistan mazar-e-sharif blue mosque.jpg",
			"afghanistan kabul slums.jpg",
			"afghanistan shot humvee mosque.jpg",
			"afghanistan herat mosque.jpg",
			"afghanistan kabul street.jpg",
			"afghanistan snow.jpg",
			"afghanistan bamyan snow.jpg",
			"afghanistan bamyan buddha hole.jpg",
			"afghanistan bamyan buddhas.jpg",
			"afghanistan herat mosque 2.jpg",
			"afghanistan snowing.jpg",
			"afghanistan horse brawl.jpg",
			"afghanistan baulk walls.jpg",
			"afghanistan TB flag.jpg",
		],
		assetItemMetaData: [
			{
				title: "Complete Afghanistan Collection (21 Clips)",
				price: 39,
				thumbnail: "afghanistan/afghanmain.jpg",
				link: "https://franklinvmoon.gumroad.com/l/kraynl",
				created: 1750143316,
				tags: [""],
				isPack: true,
			},
			{
				title: "Balkh Green Mosque",
				price: 5,
				thumbnail: "afghanistan/Balkh Green Mosque.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/svddx",
				created: 1750143317,
				tags: [""],
			},
			{
				title: "Balkh Walls",
				price: 5,
				thumbnail: "afghanistan/Balkh Walls 1.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/fnnoi",
				created: 1750143075,
				tags: [""],
			},
			{
				title: "Balkh Walls 2",
				price: 5,
				thumbnail: "afghanistan/Balkh Walls 2.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/tksrr",
				created: 1750143032,
				tags: [""],
			},
			{
				title: "Bamyan Band-e-Amir",
				price: 5,
				thumbnail: "afghanistan/Bamyan Band-e-Amir.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/pcyrhh",
				created: 1750143151,
				tags: [""],
			},
			{
				title: "Bamyan Buddha",
				price: 15,
				thumbnail: "afghanistan/Bamyan Buddha 1.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/cyuwc",
				created: 1750143260,
				tags: [""],
			},
			{
				title: "Bamyan Buddha 2",
				price: 15,
				thumbnail: "afghanistan/Bamyan Buddha 2.jpg",
				length: 12,
				link: "https://franklinvmoon.gumroad.com/l/osmult",
				created: 1750143197,
				tags: [""],
			},
			{
				title: "Bamyan Gholghola City",
				price: 10,
				thumbnail: "afghanistan/Bamyan Gholghola City.jpg",
				length: 10,
				link: "https://franklinvmoon.gumroad.com/l/cmudi",
				created: 1750143301,
				tags: [""],
			},
			{
				title: "Bamyan Shahr-e-Zohak",
				price: 5,
				thumbnail: "afghanistan/Bamyan Shahr-e-Zohak.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/vqlzi",
				created: 1750143636,
				tags: [""],
			},
			{
				title: "Herat Citadel",
				price: 5,
				thumbnail: "afghanistan/Herat Citadel 1.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/uemeo",
				created: 1750143337,
				tags: [""],
			},
			{
				title: "Herat Citadel 2",
				price: 5,
				thumbnail: "afghanistan/Herat Citadel 2.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/bjaii",
				created: 1750143460,
				tags: [""],
			},
			{
				title: "Herat Citadel 3",
				price: 10,
				thumbnail: "afghanistan/Herat Citadel 3.jpg",
				length: 2,
				link: "https://franklinvmoon.gumroad.com/l/zvmyl",
				created: 1750143588,
				tags: [""],
			},
			{
				title: "Herat Gawhar Shad Mausoleum",
				price: 5,
				thumbnail: "afghanistan/Herat Gawhar Shad Mausoleum 1.jpg",
				length: 10,
				link: "https://franklinvmoon.gumroad.com/l/rwgsw",
				created: 1750143121,
				tags: [""],
			},
			{
				title: "Herat Gawhar Shad Mausoleum 2",
				price: 5,
				thumbnail: "afghanistan/Herat Gawhar Shad Mausoleum 2.jpg",
				length: 7,
				link: "https://franklinvmoon.gumroad.com/l/jtvze",
				created: 1750143060,
				tags: [""],
			},
			{
				title: "Herat Khwaja Abdullah Ansari Shrine",
				price: 10,
				thumbnail: "afghanistan/Herat Khwaja Abdullah Ansari Shrine.jpg",
				length: 12,
				link: "https://franklinvmoon.gumroad.com/l/uovkc",
				created: 1750143007,
				tags: [""],
			},
			{
				title: "Kabul Park",
				price: 5,
				thumbnail: "afghanistan/Kabul Park.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/rtzyx",
				created: 1750143478,
				tags: [""],
			},
			{
				title: "Kabul Roundabout",
				price: 5,
				thumbnail: "afghanistan/Kabul Roundabout.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/jwxnd",
				created: 1750143613,
				tags: [""],
			},
			{
				title: "Kabul Walls",
				price: 5,
				thumbnail: "afghanistan/Kabul Walls.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/pwlqe",
				created: 1750142955,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi",
				price: 10,
				thumbnail: "afghanistan/Mazar-e-Sharif Buzkashi Grounds 1.jpg",
				length: 18,
				link: "https://franklinvmoon.gumroad.com/l/efmzeu",
				created: 1750143574,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi 2",
				price: 10,
				thumbnail: "afghanistan/Mazar-e-Sharif Buzkashi Grounds 2.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/flzob",
				created: 1750143374,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi 3",
				price: 10,
				thumbnail: "afghanistan/Mazar-e-Sharif Buzkashi Grounds 3.jpg",
				length: 11,
				link: "https://franklinvmoon.gumroad.com/l/zzdipq",
				created: 1750143442,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Hazrat Ali",
				price: 5,
				thumbnail: "afghanistan/Mazar-e-Sharif Hazrat Ali.jpg",
				length: 9,
				link: "https://franklinvmoon.gumroad.com/l/qyoaoy",
				created: 1750143235,
				tags: [""],
			},
		],
	},
	{
		title: "Bangladesh",
		thumbnail: "bangladeshmain.jpg",
		hostedLink: "bangladesh",
		assetItemMetaData: [],
		wallpapers: [],
	},
	{
		title: "Bhutan",
		thumbnail: "bhutanmain.jpg",
		hostedLink: "bhutan",
		assetItemMetaData: [],
		wallpapers: [],
	},
	{
		title: "Iran",
		thumbnail: "iranmain.jpg",
		hostedLink: "iran",
		assetItemMetaData: [],
		wallpapers: [],
	},
	{
		title: "Myanmar",
		thumbnail: "myanmarmain.jpg",
		hostedLink: "myanmar",
		assetItemMetaData: [],
		wallpapers: [],
	},
	{
		title: "Syria",
		thumbnail: "syriamain.jpg",
		hostedLink: "syria",
		assetItemMetaData: [],
		wallpapers: [],
	},
];
