import { CameraName, SFFilters, StockFootageCollection } from "../stock/types";

export const stockFootageCollection: StockFootageCollection[] = [
	{
		title: "Afghanistan",
		thumbnail: "afghanistan",
		cover: "afghanHorses",
		collectionItems: [
			{
				file: "Mazar_E_Sharif_Buzkashi_Grounds_1",
				price: 20,
				thumbnail: "Mazar_E_Sharif_Buzkashi_Grounds_1",
				created: "28th February 2025",
				country: "Afghanistan",
				location: "Mazar-i-Sharif, Buzkashi Ground",
				mapMarker: "https://maps.app.goo.gl/3Qnw4u7ZhebV2xrD6",
				cameraUsed: CameraName.Pixel6ProTelephoto,
				filters: [SFFilters.UHD],
				description:
					"Gripping equestrian battle of riders and horses to secure the goat carcuss and score, wining huge prizes",
				keywords: [
					"people",
					"real time",
					"day",
					"6 or more people",
					"crowd",
					"natural lighting",
					"travel",
					"exterior",
					"walking",
					"male",
					"tourism",
					"horse",
					"group",
					"history",
					"sport",
					"outdoors",
					"buzkashi",
					"Mazar-i-Sharif",
					"Mazar-e-Sharif",
					"Afghanistan",
					"Central Asia",
					"horsemen",
					"carcass",
					"midday",
					"spectator",
					"traditional sport",
					"equestrian",
					"competition",
					"tradition",
					"game",
					"action",
					"conflict",
					"intensity",
					"livestock",
					"animal",
					"war",
					"rider",
					"skill",
					"strength",
					"teamwork",
					"national sport",
					"cultural heritage",
					"local life",
					"cultural performance",
					"regional sport",
					"horsemanship tradition",
					"non-political",
					"authentic",
					"real life",
					"travel (cultural)",
					"tourism (cultural)",
				],
			},
		],
	},
];
