import { TravelVideoMetaData } from "../travel/types";

export const publicCDNVideoUrl = "https://d3atatnx15erez.cloudfront.net/";
export const insecureRestrictionKey = "adventuretime";

export const travelVideoMetaData: TravelVideoMetaData[] = [
	{
		title: "China",
		year: 2017,
		hostedLink: "china",
		link: "china",
		backupLink:
			"https://drive.google.com/file/d/1__yqFNE4pn1qb4HQaL8gVa0NptzwEXYm/view?usp=sharing",
		restricted: false,
	},
	{
		title: "Nepal",
		year: 2018,
		hostedLink: "nepal",
		link: "nepal",
		backupLink:
			"https://drive.google.com/file/d/146q73zYYICz71NWoRBZuaVU5cln0VilL/view?usp=sharing",
		restricted: false,
	},
	{
		title: "Indonesia",
		year: 2019,
		hostedLink: "indonesia",
		link: "indonesia",
		backupLink:
			"https://drive.google.com/file/d/161aw78gaH8lEHlF2H-NR6B4LHnPr6rqI/view?usp=sharing",
		restricted: true,
	},
	{
		title: "Malaysia & Singapore",
		year: 2019,
		hostedLink: "malaysiasingapore",
		link: "malaysia-singapore",
		backupLink:
			"https://drive.google.com/file/d/1slogZWzJDTvzFp7atsPj9UJZuhclFuuR/view?usp=sharing",
		restricted: false,
	},
	{
		title: "New Zealand",
		year: 2019,
		hostedLink: "newzealand",
		link: "new-zealand",
		backupLink:
			"https://drive.google.com/file/d/1LGP1-IFj6axNRF2Kmw3WAiThw4CevFjs/view?usp=sharing",
		restricted: false,
	},
	{
		title: "Japan",
		year: 2020,
		hostedLink: "japan",
		link: "japan",
		backupLink:
			"https://drive.google.com/file/d/1HYxY0t2p0f8vABavBfSSj2pGUW05x7Y6/view?usp=sharing",
		restricted: false,
	},
	{
		title: "Thailand",
		year: 2022,
		hostedLink: "thailand",
		link: "thailand",
		backupLink:
			"https://drive.google.com/file/d/1ib8sK0NSWDo4NMRhqlJIHqwD6iu7xI6O/view?usp=sharing",
		restricted: false,
	},
	{
		title: "South Korea",
		year: 2022,
		hostedLink: "southkorea",
		link: "south-korea",
		backupLink:
			"https://drive.google.com/file/d/1G2emPhFNvHV9JPtF_hyl0WbOzKLkTXOk/view?usp=sharing",
		restricted: true,
	},
	{
		title: "Sri Lanka",
		year: 2022,
		hostedLink: "srilanka",
		link: "sri-lanka",
		backupLink:
			"https://drive.google.com/file/d/13gOi8XTHFCI-cInwD4hBGF1kblg0MJDa/view?usp=sharing",
		restricted: true,
	},
	{
		title: "United Arab Emirates",
		year: 2022,
		hostedLink: "uae",
		link: "uae",
		backupLink:
			"https://drive.google.com/file/d/1_Xv-xTZ054zoTKmPaPVmQgc49qH-Exfv/view?usp=sharing",
		restricted: true,
	},
	{
		title: "Fiji",
		year: 2022,
		hostedLink: "fiji",
		link: "fiji",
		backupLink:
			"https://drive.google.com/file/d/1tNjLg89P1bEa-q9rQu0_cCDQqCk7t9me/view?usp=sharing",
		restricted: true,
	},
	{
		title: "Cambodia, Laos and Vietnam",
		year: 2023,
		hostedLink: "cambodialaosvietnam",
		link: "cambodia-laos-vietnam",
		backupLink:
			"https://drive.google.com/file/d/1aurSN-frLRNGPnGkr7GXN3yz87dMCvh6/view?usp=sharing",
		restricted: true,
		reelLinks: ["https://www.instagram.com/reel/Cy-7c3yLFuE/"],
		instagramLinks: [
			"https://www.instagram.com/p/CpfKGORr12k/?img_index=1",
			"https://www.instagram.com/p/Cph3kEdLXFh/?img_index=1",
			"https://www.instagram.com/p/CpolhlDLS87/?img_index=1",
			"https://www.instagram.com/p/CpvKryKr-qx/?img_index=1",
			"https://www.instagram.com/p/Cpxt4mHJiwQ/?img_index=1",
			"https://www.instagram.com/p/Cp23tBbPq61/?img_index=1",
			"https://www.instagram.com/p/CqD9tCMBNH4/?img_index=1",
			"https://www.instagram.com/p/CqJB8WLhyXZ/?img_index=1",
		],
	},
	{
		title: "Taiwan, Hong Kong and Macau",
		year: 2023,
		hostedLink: "taiwanhongkongmacau",
		link: "taiwan-hong-kong-macau",
		backupLink:
			"https://drive.google.com/file/d/1nriFFLbIwip3znUctlaBzX_eu-MyBe-R/view?usp=sharing",
		restricted: false,
		reelLinks: ["https://www.instagram.com/reel/CzTjUurL-5y/"],
		instagramLinks: [
			"https://www.instagram.com/p/CqiBx-QLGMf/?img_index=1",
			"https://www.instagram.com/p/CqkX4dSLqCk/?img_index=1",
			"https://www.instagram.com/p/CqqBXJaJep-/?img_index=1",
			"https://www.instagram.com/p/CqyWFoph6Jq/?img_index=1",
			"https://www.instagram.com/p/Cq0pE9FJtcd/?img_index=1",
			"https://www.instagram.com/p/Cq0vJz4v5Tl/?img_index=1",
			"https://www.instagram.com/p/Cq3MLbyJlQd/?img_index=1",
			"https://www.instagram.com/p/Cq8lp99BCD3/?img_index=1",
			"https://www.instagram.com/p/Cq-ILXzrnjp/?img_index=1",
		],
	},
	{
		title: "India",
		year: 2023,
		hostedLink: "india",
		link: "india",
		backupLink:
			"https://drive.google.com/file/d/1oIID6SrD0xK-EJ0l0aWIfGi4gdUwq9Ky/view?usp=sharing",
		restricted: false,
		reelLinks: ["https://www.instagram.com/reel/C2uwpY2LGcS/"],
		instagramLinks: [
			"https://www.instagram.com/p/CrGLo47LBNk/?img_index=1",
			"https://www.instagram.com/p/CrK67cDLP-r/?img_index=1",
			"https://www.instagram.com/p/CrQ5ycepdzf/?img_index=1",
			"https://www.instagram.com/p/CrVxYQFLf6t/?img_index=1",
			"https://www.instagram.com/p/CrbOJJRs4nj/?img_index=1",
			"https://www.instagram.com/p/Crd6nDPvlww/?img_index=1",
			"https://www.instagram.com/p/CrklzD8rMhX/?img_index=1",
			"https://www.instagram.com/p/CroDXezM3-G/?img_index=1",
			"https://www.instagram.com/p/CrwEXR7y_k8/?img_index=1",
			"https://www.instagram.com/p/Cr5hNUxL-V8/?img_index=1",
			"https://www.instagram.com/p/Cr884JABum8/?img_index=1",
			"https://www.instagram.com/p/Cr_1nIPhkw1/?img_index=1",
		],
	},
	{
		title: "Oman",
		year: 2023,
		hostedLink: "oman",
		link: "oman",
		backupLink:
			"https://drive.google.com/file/d/1FQux8SdlnL-idrPsbt2uF5OAfJW57CZa/view?usp=sharing",
		restricted: true,
		reelLinks: ["https://www.instagram.com/reel/C4DkLuqJ3AR/"],
		instagramLinks: [
			"https://www.instagram.com/p/CsHbTJ8h78G/?img_index=1",
			"https://www.instagram.com/p/CsNvb55M2t8/?img_index=1",
			"https://www.instagram.com/p/CsTFmJHMw5w/?img_index=1",
		],
	},
	{
		title: "Kuwait and Iraqi Kurdistan",
		year: 2023,
		hostedLink: "kuwaitiraq",
		link: "kuwait-iraqi-kurdistan",
		backupLink:
			"https://drive.google.com/file/d/1iEokNO7kkZfvBYcrbPfTI3Fag_mPc-3b/view?usp=sharing",
		restricted: true,
		reelLinks: ["https://www.instagram.com/reel/C5OA27DJ5Tx/"],
		instagramLinks: [
			"https://www.instagram.com/p/CsW4lzgL_Ec/?img_index=1",
			"https://www.instagram.com/p/CseTQptLmaT/?img_index=1",
			"https://www.instagram.com/p/CshQp_fr_fb/?img_index=1",
			"https://www.instagram.com/p/Csjuc4SrOXF/?img_index=1",
			"https://www.instagram.com/p/CsrDDjhv8s4/?img_index=1",
		],
	},
	{
		title: "Jordan",
		year: 2023,
		hostedLink: "jordan",
		link: "jordan",
		backupLink:
			"https://drive.google.com/file/d/1lSx97jlDxrnmCy6zBw649LKZPN7zh0-v/view?usp=sharing",
		restricted: false,
		reelLinks: ["https://www.instagram.com/reel/C750R5uphGc/"],
		instagramLinks: [
			"https://www.instagram.com/p/Csv3RWrszXo/?img_index=1",
			"https://www.instagram.com/p/Cs37edtMV5K/?img_index=1",
			"https://www.instagram.com/p/Cs58X-UpzwX/?img_index=1",
			"https://www.instagram.com/p/Cs5-RJvpXRn/?img_index=1",
			"https://www.instagram.com/p/Cs8X9kSLP7_/?img_index=1",
			"https://www.instagram.com/p/Cs_0-aRPvG5/?img_index=1",
		],
	},
	{
		title: "Saudi Arabia and Bahrain",
		year: 2023,
		hostedLink: "saudiarabia",
		link: "saudi-arabia-bahrain",
		backupLink:
			"https://drive.google.com/file/d/1AWtoY6ESbq3ekar6CTzBr9NDTL6x9C2K/view?usp=sharing",
		restricted: true,
		reelLinks: ["https://www.instagram.com/reel/C8L4ml_JkSf/"],
		instagramLinks: [
			"https://www.instagram.com/p/CtB7kMjrehP/?img_index=1",
			"https://www.instagram.com/p/CtMUbqlprRL/?img_index=1",
			"https://www.instagram.com/p/CtRlrampitt/?img_index=1",
		],
	},
	{
		title: "Iran",
		year: 2023,
		hostedLink: "iran",
		link: "iran",
		backupLink:
			"https://drive.google.com/file/d/16QMDQAyduOzPYYQLAOPydbsKMXfNIZmD/view?usp=sharing",
		restricted: false,
		reelLinks: ["https://www.instagram.com/reel/C89yh6IS-3R/"],
		instagramLinks: [
			"https://www.instagram.com/p/CtUbIIUrCuB/?img_index=1",
			"https://www.instagram.com/p/CtXWowqpCaG/?img_index=1",
			"https://www.instagram.com/p/CtaALBqLgzO/?img_index=1",
			"https://www.instagram.com/p/CtcU9GaJw7D/?img_index=1",
			"https://www.instagram.com/p/CtkDysGpNU1/?img_index=1",
			"https://www.instagram.com/p/CtmgnktJcUn/?img_index=1",
			"https://www.instagram.com/p/CtrhaHNr2J9/?img_index=1",
		],
	},
	{
		title: "Armenia, Georgia & Azerbaijan",
		year: 2023,
		hostedLink: "armeniageorgiaazerbaijan",
		link: "armenia-georgia-azerbaijan",
		backupLink:
			"https://drive.google.com/file/d/1z3K7_CSrSVdOv3YAqw0nva_I9IJVbRB6/view?usp=sharing",
		restricted: false,
		reelLinks: ["https://www.instagram.com/reel/C-w6PVhib9V/?hl=en"],
		instagramLinks: [
			"https://www.instagram.com/p/CtupJTxLpN2/?hl=en",
			"https://www.instagram.com/p/CtxSF9Isjco/?hl=en",
			"https://www.instagram.com/p/Ct4xNkmrOpm/?hl=en",
			"https://www.instagram.com/p/Ct7HgwUr25t/?hl=en",
			"https://www.instagram.com/p/Ct-JkPVsuaU/?hl=en",
			"https://www.instagram.com/p/CuDSxN0shnk/?hl=en",
			"https://www.instagram.com/p/CuFqXixr8ES/?hl=en",
			"https://www.instagram.com/p/CuKiuoBLq6p/?hl=en",
			"https://www.instagram.com/p/CuQET6trR_g/?hl=en",
			"https://www.instagram.com/p/CuWSIkQMRzy/?hl=en",
			"https://www.instagram.com/p/CuWWQVoM7FU/?hl=en",
			"https://www.instagram.com/p/CubhrkpMmYm/?hl=en",
		],
	},
	{
		title: "Greece",
		year: 2023,
		hostedLink: "greece",
		link: "greece",
		backupLink: 
			"https://drive.google.com/file/d/1MeR97lcIr9pICYWFPE2JrSuLcSnFD88z/view?usp=sharing",
		restricted: false,
		reelLinks: ["https://www.instagram.com/reel/C_PcOfOCX4E/?hl=en"],
		instagramLinks: [
			"https://www.instagram.com/p/CufoGNOsExu/?hl=en",
			"https://www.instagram.com/p/CuklIluLnZE/?hl=en",
			"https://www.instagram.com/p/CuknIYYrTRi/?hl=en",
			"https://www.instagram.com/p/Cup18pisDpr/?hl=en",
			"https://www.instagram.com/p/CutX6yNsmrW/?hl=en",
			"https://www.instagram.com/p/CuxVBypLGrt/?hl=en",
			"https://www.instagram.com/p/CuxaFY_rTD3/?hl=en",
			"https://www.instagram.com/p/Cu1rOL5M2B5/?hl=en",
			"https://www.instagram.com/p/Cu5JTCbrApq/?hl=en"
		],
	},
	{
		title: "Turkey",
		year: 2023,
		hostedLink: "turkey",
		link: "turkey",
		restricted: false,
		instagramLinks: [
			"https://www.instagram.com/p/Cu9PmFaLhfp/?hl=en",
			"https://www.instagram.com/p/CvFEUc1sqd7/?hl=en",
			"https://www.instagram.com/p/CvQnIUlNDkk/?hl=en",
			"https://www.instagram.com/p/CvRpULzsPWw/?hl=en",
			"https://www.instagram.com/p/CvVZxBmrnNO/?hl=en",
			"https://www.instagram.com/p/CvYKenvMW31/?hl=en",
			"https://www.instagram.com/p/CvcCKJzMUAD/?hl=en",
			"https://www.instagram.com/p/CviNxqQrVSL/?hl=en",
		],
		backupLink: 
			"https://drive.google.com/file/d/1z3NA6uaGaobUKxNo6YB3QSyt5HI2IbwJ/view?usp=sharing",
		reelLinks: ["https://www.instagram.com/reel/C_cuUwoigGb/?hl=en"],
		newestVideo: true
	},
	{
		title: "Lebanon",
		year: 2023,
		hostedLink: "lebanon",
		link: "lebanon",
		restricted: false,
		instagramLinks: [
			"https://www.instagram.com/p/CvspxJLrFVg/?hl=en",
			"https://www.instagram.com/p/CvzNnEssv_r/?hl=en",
			"https://www.instagram.com/p/CvzO2Pxs0os/?hl=en",
			"https://www.instagram.com/p/Cv0gI5yLV3q/?hl=en",
		],
	},
	{
		title: "Syria",
		year: 2023,
		hostedLink: "syria",
		link: "syria",
		restricted: false,
		instagramLinks: [
			"https://www.instagram.com/p/Cv66XjcLuCI/?hl=en",
			"https://www.instagram.com/p/Cv9eJaMsQ1o/?hl=en",
			"https://www.instagram.com/p/CwCTJLKMRo0/?hl=en",
			"https://www.instagram.com/p/CwF09q0spyl/?hl=en",
			"https://www.instagram.com/p/CwNnPkVMIUc/?hl=en",
		],
	},
	{
		title: "Cyprus",
		year: 2023,
		hostedLink: "cyprus",
		link: "cyprus",
		restricted: false,
		instagramLinks: [
			"https://www.instagram.com/p/CwTBSZ8rP6c/?hl=en",
			"https://www.instagram.com/p/CwVuLVvrgWP/?hl=en",
		],
	},
	{
		title: "Israel & Palestine",
		year: 2023,
		hostedLink: "israelpalestine",
		link: "israel-and-palestine",
		restricted: false,
		instagramLinks: [
			"https://www.instagram.com/p/CwYWLKNr2nj/?hl=en",
			"https://www.instagram.com/p/CwfOOKisfk6/?hl=en",
			"https://www.instagram.com/p/Cwk0xLwsCd_/?hl=en",
			"https://www.instagram.com/p/CwnqtIaLVUC/?hl=en",
			"https://www.instagram.com/p/CwuCqhUMNAd/?hl=en",
			"https://www.instagram.com/p/Cwzr9nZLCDu/?hl=en",
		],
	},
	{
		title: "Philippines & Brunei",
		year: 2024,
		hostedLink: "philippinesbrunei",
		link: "philippines-and-brunei",
		restricted: false,
		instagramLinks: [
			"https://www.instagram.com/p/C0qMrfyrRhi/?hl=en",
			"https://www.instagram.com/p/C1EZPPPrN87/?hl=en",
			"https://www.instagram.com/p/C1Q2UQcLqS-/?hl=en",
		],
	},
	{
		title: "Timor-Leste",
		year: 2024,
		hostedLink: "timorleste",
		link: "timor-leste",
		restricted: false,
		instagramLinks: [
			"https://www.instagram.com/p/C-RGiELTbxA/?hl=en",
			"https://www.instagram.com/p/C-U4hPnzsoJ/?hl=en",
			"https://www.instagram.com/p/C-ZpKlvzLk3/?hl=en",
		],
	},
];
