import { Languages, Tags, Topic, TutorialMetaData } from "../tutorials/types";

export const tutorialMetaData: TutorialMetaData[] = [
	{
		title: "React-Redux Refresher",
		link: "react-redux-refresher",
		notionPage: "b2b95c4552a24526ba3fec209cb1eb4a",
		created: 1667982722,
		thumbnail: "/tutorials/redux-ducks.png",
		subTitle:
			"Get upto speed on how redux flows, the testing pattern ducks and simple unit testing",
		topic: Topic.Programming,
		languages: [Languages.Javascript],
		tags: [Tags.QuickStart],
	},
	{
		title: "Revert a Commit",
		link: "revert-commit",
		notionPage: "9d8e0e3197544913af8ab782a011d4f2",
		created: 1664495954,
		thumbnail: "/tutorials/revert-commit.jpg",
		subTitle:
			"Keep calm and fix the pipeline with these super simple instructions",
		topic: Topic.Programming,
		languages: [],
		tags: [Tags.StepByStep],
	},
	{
		title: "Provider Wrapping with Souvlaki",
		link: "provider-wrapping-with-souvlaki",
		notionPage: "5bd25204d97e4e8aa6e5946619973ba3",
		created: 1663809960,
		thumbnail: "/tutorials/souvlaki-wrap.jpg",
		subTitle: "Simpler reusable provider wrappers for all your unit test needs",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.StepByStep],
	},
	{
		title: "Cleaner Conditional Component Rendering",
		link: "clearer-conditional-rendering",
		notionPage: "578b462fff1b45f89a064d5eafe61c5f",
		created: 1663151345,
		thumbnail: "/tutorials/showif.jpeg",
		subTitle:
			"Replace messy ternaries and booleans with this neat component wrapper",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Type Validate an API Fetch Call",
		link: "fetch-api-type-validation",
		notionPage: "44f4f50236114c078b83e55a4fb8e9c5",
		created: 1659149375,
		thumbnail: "/tutorials/api-validation.png",
		subTitle: "Use io-ts to verify incoming data",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.StepByStep],
	},
	{
		title: "Manipulate Images using ImageMagick",
		link: "convert-resize-with-imagemagick",
		notionPage: "0a6b86c59ce54c5480c67e7edd5b59ba",
		created: 1656459369,
		thumbnail: "/tutorials/convert-resize.png",
		subTitle: "Easy tool to rescale & change image file types",
		topic: Topic.Programming,
		tags: [Tags.CodeBlock],
	},
	{
		title: "Dockerize Your Repository",
		link: "dockerize-your-repo",
		notionPage: "c4ca92237cc4434cbc30119b104e9e87",
		created: 1639982643,
		thumbnail: "/tutorials/dockerize.png",
		subTitle: "Understand and build containers that run your app anywhere",
		topic: Topic.Infrastructure,
		languages: [Languages.Docker],
		tags: [Tags.StepByStep],
	},
	{
		title: "Terminal Commands Cheat Sheet",
		link: "command-cheat-sheet",
		notionPage: "ea55e3b6a5f54b50abdc456bedc4b80a",
		created: 1639982642,
		thumbnail: "/tutorials/terminal.png",
		subTitle: "List of common commands you'll actually use",
		topic: Topic.Programming,
		languages: [],
		tags: [],
	},
	{
		title: "Deploy Containers to AWS with Terraform",
		link: "deploy-to-aws-ec2-using-terraform-and-docker",
		notionPage: "4d5154f6347a46d280c19f2d8ad9de4f",
		created: 1639982641,
		thumbnail: "/tutorials/aws-docker-terraform.png",
		subTitle:
			"Step-by-step instructions to spin up AWS and host your project using Terraform",
		topic: Topic.Infrastructure,
		languages: [Languages.Docker, Languages.Terraform],
		tags: [Tags.StepByStep],
	},
	{
		title: "Quickstart: NextJS",
		link: "quickly-setup-next-js-with-typescript",
		notionPage: "eb6acd5b26d3416c9372be89cae2b05d",
		created: 1639982640,
		thumbnail: "/tutorials/quickstart-next.png",
		subTitle: "Get up-and-running with a cleaned up but ready to go NextJs app",
		topic: Topic.Programming,
		languages: [Languages.Typescript, Languages.Javascript],
		tags: [Tags.QuickStart],
	},
	{
		title: "Snippet: Test a Thrown Error",
		link: "test-thrown-error",
		notionPage: "1ad3c64947224e5e9acf4a09e9086a5b",
		created: 1639982639,
		thumbnail: "/tutorials/test-thrown-error.png",
		subTitle: "Easiest way to test your thrown errors are behaving correctly",
		topic: Topic.Programming,
		languages: [Languages.Typescript, Languages.Javascript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Override Props for UI Tests",
		link: "override-props-for-ui-tests",
		notionPage: "c5923b0c20964128be7178d42d7e884b",
		created: 1639982638,
		thumbnail: "/tutorials/override-test-props.png",
		subTitle:
			"Using a single source for test data and changing only whats needed.",
		topic: Topic.Programming,
		languages: [Languages.Typescript, Languages.Javascript],
		tags: [Tags.StepByStep],
	},
	{
		title: "Snippet: Repeat One Test with New Variables",
		link: "repeat-test-with-new-variables",
		notionPage: "f5255703bba04229aafded995e423d25",
		created: 1639982637,
		thumbnail: "/tutorials/repeat-test.jpg",
		subTitle:
			"Using it.each you can pass new values, to test various combinations of inputs and outputs",
		topic: Topic.Programming,
		languages: [Languages.Typescript, Languages.Javascript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Project Wall: Single Source of Truth",
		link: "project-wall-single-source-of-truth",
		notionPage: "a036e1f8f1d844a5a512dc6d7a011ccf",
		created: 1639982636,
		thumbnail: "/tutorials/project-wall.jpg",
		subTitle: "Increase distributed team collaboration with a virtual wall",
		topic: Topic.Agile,
		tags: [Tags.Essay],
	},
	{
		title: "Snippet: Create Array with Only Truthy Values",
		link: "filter-array-with-only-truthy-values",
		notionPage: "f546bb620f29415ba0d9b3b6e5bac748",
		created: 1639982635,
		thumbnail: "/tutorials/array-filter.png",
		subTitle:
			"Generate an array of values but only include ones that exists, excluding undefined",
		topic: Topic.Programming,
		languages: [Languages.Javascript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Snippet: Retry Any Function Recursively",
		link: "retry-recursively",
		notionPage: "88e2d51cb8d74f9a9eb561185f16d322",
		created: 1639982634,
		thumbnail: "/tutorials/retry-recursively.jpg",
		subTitle: "Rerun Function n number of times or handle a thrown error",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Snippet: Run GraphQL and Express Together",
		link: "run-graphql-and-express",
		notionPage: "0e6becfb9fb64c6b96f4ef66742ac3e9",
		created: 1639982633,
		thumbnail: "/tutorials/graphql-express.png",
		subTitle:
			"Easily run two separate backend apis in the same shared code base",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Snippet: Catch Error By Type",
		link: "try-catch-by-type",
		notionPage: "898854cc62d84573807f8da823304ea0",
		created: 1639982632,
		thumbnail: "/tutorials/try-catch.png",
		subTitle:
			"Handle showing an error to your backend or UI via a simple try/catch",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Quickstart: Spring with Java",
		link: "quickstart-java-with-spring",
		notionPage: "0872f80487ae46eb9f233609b0d0ece0",
		created: 1639982535,
		thumbnail: "/tutorials/java-spring.png",
		subTitle:
			"Step by Step guide to building a Spring Java webapp using spring boot and understand it's basic uses",
		topic: Topic.Programming,
		languages: [Languages.Java],
		tags: [Tags.StepByStep],
	},
	{
		title: "Core React Concepts",
		link: "core-react-concepts",
		notionPage: "6b07a4eeb9e44def926307fa42a38a66",
		created: 1639982534,
		thumbnail: "/tutorials/react-quickstart.png",
		subTitle:
			"Explanation and usage of foundational React topics such as props, hooks, routes, forms etc",
		topic: Topic.Programming,
		languages: [Languages.Javascript, Languages.Typescript],
		tags: [Tags.Essay],
	},
	{
		title: "Feature Toggles Checklist",
		link: "feature-toggle-checklist",
		notionPage: "9f41249d7fbe4e70a14e12fdb7308e0e",
		created: 1639982533,
		thumbnail: "/tutorials/feature-toggle.png",
		subTitle:
			"When building feature toggles, follow these checks to ensure you don't over-complicate things",
		topic: Topic.Programming,
		languages: [],
		tags: [Tags.StepByStep],
	},
	{
		title: "RESTful API Design",
		link: "restful-api-design",
		notionPage: "77d91ff0c0274cb7aeeb3491221b8952",
		created: 1639982532,
		thumbnail: "/tutorials/rest-api.jpeg",
		subTitle:
			"Basic REST API concepts, including resource design, HTTP Codes, Headers etc",
		topic: Topic.Programming,
		languages: [],
		tags: [Tags.Essay],
	},
	{
		title: "Estimation and Pitfalls",
		link: "estimation-and-pitfalls",
		notionPage: "9835c35bb3e34d86b890d90fbb5c2599",
		created: 1639982531,
		thumbnail: "/tutorials/estimation-pitfalls.jpeg",
		subTitle:
			"A discussion on the realities of estimation and common pitfalls teams may find themselves in",
		topic: Topic.Agile,
		languages: [],
		tags: [Tags.Essay],
	},
	{
		title: "How To Give Feedback",
		link: "how-to-give-feedback",
		notionPage: "09727dd836ca4bf9b22ef84d99ae509b",
		created: 1639982529,
		thumbnail: "/tutorials/feedback.jpeg",
		subTitle:
			"A helpful guide to working out the right feedback to give. Includes a score card to help you brainstorm",
		topic: Topic.Agile,
		languages: [],
		tags: [Tags.StepByStep, Tags.Essay],
	},
	{
		title: "Planning a Showcase",
		link: "checklist-planning-showcase",
		notionPage: "04f65ce6da4143dc840e8b6d07b56e0e",
		created: 1639982528,
		thumbnail: "/tutorials/presentation-showcase.jpeg",
		subTitle:
			"What, Who, Why, When and How to run an outstanding Showcase to your Product Owner",
		topic: Topic.Agile,
		languages: [],
		tags: [Tags.StepByStep],
	},
];
