import { Languages, Tags, Topic, TutorialMetaData } from "../tutorials/types";

export const tutorialMetaData: TutorialMetaData[] = [
	{
		title: "Kubernetes Essentials",
		link: "kubernetes-essentials",
		notionPage: "36d077d40d5c4c809adecc1f13f4978c",
		created: 1700712512,
		thumbnail: "/tutorials/kubernetes.png",
		subTitle:
			"Getting started with Kubernetes, covering all the basic skills required by a Kubernetes Administrator",
		topic: Topic.Infrastructure,
		tags: [Tags.StepByStep, Tags.CodeBlock],
	},
	{
		title: "AWS Cloud Practitioner Reference",
		link: "aws-cloud-practitioner-reference",
		notionPage: "e2836f55924d4582a22fe1c51b019a12",
		created: 1699851048,
		thumbnail: "/tutorials/cloud-prac.png",
		subTitle:
			"Overview of all the expected knowledge, ideal for the official Cloud Practitioner certificate exam",
		topic: Topic.Infrastructure,
		tags: [Tags.Essay],
	},
	{
		title: "Backpackers Guide To Persia",
		link: "persia-guide",
		notionPage: "9248eed5462d41b9afac25112f7526b3",
		created: 1698905456,
		thumbnail: "/tutorials/iran.png",
		subTitle:
			"How to get to Iran and make the most of your time there. Covers challenges, concerns and things to do",
		topic: Topic.Article,
		tags: [Tags.Essay],
	},
	{
		title: "Advanced Prompt Engineering",
		link: "prompt-engineering",
		notionPage: "1ec344d590fc4056b90328aaaf0f9663",
		created: 1698905329,
		thumbnail: "/tutorials/prompt.png",
		subTitle:
			"Construct prompts to guide large language models (LLMs) towards a desired outcome",
		topic: Topic.Programming,
		tags: [Tags.CodeBlock],
	},
	{
		title: "Bash Scripting",
		link: "bash-scripting",
		notionPage: "039a3a1de59741639174939df0f4c20c",
		created: 1698220136,
		thumbnail: "/tutorials/scroll.png",
		subTitle:
			"Cheatsheet for bash, vim and some general terminal inputs",
		topic: Topic.Programming,
		tags: [Tags.CodeBlock],
	},
	{
		title: "Top Travel Hacks",
		link: "travel-hacks",
		notionPage: "10b40f8350c345df9bde0eeda7822a21",
		created: 1675825612,
		thumbnail: "/tutorials/travel-hacks.png",
		subTitle:
			"Tips and tricks to help you backpacking, save money, fly smart, enjoy things more and meet people",
		topic: Topic.Article,
		tags: [Tags.Essay, Tags.StepByStep],
	},
	{
		title: "Build a .NET REST API with C#",
		link: "dotnet-rest-api",
		notionPage: "d27ec236b7814b44a3f82051d1b973e4",
		created: 1675825611,
		thumbnail: "/tutorials/Microsoft-C-Sharp.jpeg",
		subTitle:
			"Learn common .NET patterns and conventions to build a simple rest API from scratch",
		topic: Topic.Programming,
		languages: [Languages.CSharp],
		tags: [Tags.StepByStep, Tags.QuickStart],
	},
	{
		title: "Code frontend with Emojis?",
		link: "code-with-emojis",
		notionPage: "f1c08c6df5ec4d9bbf99f4dc6a372540",
		created: 1675825610,
		thumbnail: "/tutorials/emoji.png",
		subTitle:
			"Most devs would lose their minds if you used an emoji in your code, how about we do it anyway?",
		topic: Topic.Programming,
		languages: [Languages.HTML, Languages.CSS],
		tags: [Tags.StepByStep],
	},
	{
		title: "Run scripts on AWS EC2 instance startup",
		link: "aws-run-scripts-on-startup",
		notionPage: "dd5eea1afcb447e4b82dd5843ac0f662",
		created: 1675825605,
		thumbnail: "/tutorials/aws-script.png",
		subTitle:
			"Running scripts is fairly critical when you want to automatically configure you're EC2 Instances",
		topic: Topic.Infrastructure,
		languages: [Languages.BashShell],
		tags: [Tags.CodeBlock],
	},
	{
		title: "React-Redux refresher",
		link: "react-redux-refresher",
		notionPage: "b2b95c4552a24526ba3fec209cb1eb4a",
		created: 1667982722,
		thumbnail: "/tutorials/redux-ducks.png",
		subTitle:
			"Refresh yourself on the flow of Redux, the testing methodology of Ducks, and conducting basic unit testing",
		topic: Topic.Programming,
		languages: [Languages.Javascript],
		tags: [Tags.QuickStart],
	},
	{
		title: "Calmly revert a git commit",
		link: "revert-commit",
		notionPage: "9d8e0e3197544913af8ab782a011d4f2",
		created: 1664495954,
		thumbnail: "/tutorials/revert-commit.png",
		subTitle:
			"Keep calm and address the pipeline issues through these straightforward instructions",
		topic: Topic.Programming,
		languages: [],
		tags: [Tags.StepByStep],
	},
	{
		title: "Provider wrapping with Souvlaki",
		link: "provider-wrapping-with-souvlaki",
		notionPage: "5bd25204d97e4e8aa6e5946619973ba3",
		created: 1663809960,
		thumbnail: "/tutorials/souvlaki-wrap.png",
		subTitle: "Simple reusable provider wrappers for all your unit test needs",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.StepByStep],
	},
	{
		title: "Cleaner React conditional component rendering",
		link: "clearer-conditional-rendering",
		notionPage: "578b462fff1b45f89a064d5eafe61c5f",
		created: 1663151345,
		thumbnail: "/tutorials/showif.png",
		subTitle:
			"Efficient and reusable provider wrappers to meet all of your unit testing requirements.",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Type Validate an API Fetch Call",
		link: "fetch-api-type-validation",
		notionPage: "44f4f50236114c078b83e55a4fb8e9c5",
		created: 1659149375,
		thumbnail: "/tutorials/api-validation.png",
		subTitle: "Implement the use of io-ts to validate incoming data",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.StepByStep],
	},
	{
		title: "Manipulate images using ImageMagick",
		link: "convert-resize-with-imagemagick",
		notionPage: "0a6b86c59ce54c5480c67e7edd5b59ba",
		created: 1656459369,
		thumbnail: "/tutorials/convert-resize.png",
		subTitle: "Easy tool to rescale & change image file types",
		topic: Topic.Programming,
		tags: [Tags.CodeBlock],
	},
	{
		title: "Dockerize your repository",
		link: "dockerize-your-repo",
		notionPage: "c4ca92237cc4434cbc30119b104e9e87",
		created: 1639982643,
		thumbnail: "/tutorials/dockerize.png",
		subTitle: "Understand and build containers that run your app anywhere",
		topic: Topic.Infrastructure,
		languages: [Languages.Docker],
		tags: [Tags.StepByStep],
	},
	{
		title: "Terminal commands cheat sheet",
		link: "command-cheat-sheet",
		notionPage: "ea55e3b6a5f54b50abdc456bedc4b80a",
		created: 1639982642,
		thumbnail: "/tutorials/terminal.png",
		subTitle: "List of common commands you'll actually use",
		topic: Topic.Programming,
		languages: [],
		tags: [],
	},
	{
		title: "Deploy containers to AWS with Terraform",
		link: "deploy-to-aws-ec2-using-terraform-and-docker",
		notionPage: "4d5154f6347a46d280c19f2d8ad9de4f",
		created: 1639982641,
		thumbnail: "/tutorials/aws-docker-terraform.png",
		subTitle:
			"Step-by-step instructions to spin up AWS and host your project using Terraform",
		topic: Topic.Infrastructure,
		languages: [Languages.Docker, Languages.Terraform],
		tags: [Tags.StepByStep],
	},
	{
		title: "NextJS quickstart guide",
		link: "quickly-setup-next-js-with-typescript",
		notionPage: "eb6acd5b26d3416c9372be89cae2b05d",
		created: 1639982640,
		thumbnail: "/tutorials/quickstart-next.png",
		subTitle: "Get up-and-running with a cleaned up but ready to go NextJs app",
		topic: Topic.Programming,
		languages: [Languages.Typescript, Languages.Javascript],
		tags: [Tags.QuickStart],
	},
	{
		title: "How to test a thrown error",
		link: "test-thrown-error",
		notionPage: "1ad3c64947224e5e9acf4a09e9086a5b",
		created: 1639982639,
		thumbnail: "/tutorials/test-thrown-error.png",
		subTitle: "Easiest way to test your thrown errors are behaving correctly",
		topic: Topic.Programming,
		languages: [Languages.Typescript, Languages.Javascript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Override props for UI tests",
		link: "override-props-for-ui-tests",
		notionPage: "c5923b0c20964128be7178d42d7e884b",
		created: 1639982638,
		thumbnail: "/tutorials/override-test-props.png",
		subTitle:
			"Using a single source for test data and changing only whats needed",
		topic: Topic.Programming,
		languages: [Languages.Typescript, Languages.Javascript],
		tags: [Tags.StepByStep],
	},
	{
		title: "How to repeat a single jest test with new variables",
		link: "repeat-test-with-new-variables",
		notionPage: "f5255703bba04229aafded995e423d25",
		created: 1639982637,
		thumbnail: "/tutorials/repeat-test.png",
		subTitle:
			"Using it.each you can pass new values, to test various combinations of inputs and outputs",
		topic: Topic.Programming,
		languages: [Languages.Typescript, Languages.Javascript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "The virtual project wall, a single source of truth",
		link: "project-wall-single-source-of-truth",
		notionPage: "a036e1f8f1d844a5a512dc6d7a011ccf",
		created: 1639982636,
		thumbnail: "/tutorials/project-wall.png",
		subTitle: "Increase distributed team collaboration with a virtual wall",
		topic: Topic.Agile,
		tags: [Tags.Essay],
	},
	{
		title: "How to create a javascript array with only truthy values",
		link: "filter-array-with-only-truthy-values",
		notionPage: "f546bb620f29415ba0d9b3b6e5bac748",
		created: 1639982635,
		thumbnail: "/tutorials/array-filter.png",
		subTitle:
			"Generate an array of values but only include ones that exists, excluding undefined",
		topic: Topic.Programming,
		languages: [Languages.Javascript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "How to retry any javascript function recursively",
		link: "retry-recursively",
		notionPage: "88e2d51cb8d74f9a9eb561185f16d322",
		created: 1639982634,
		thumbnail: "/tutorials/retry-recursively.png",
		subTitle: "Rerun Function n number of times or handle a thrown error",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "Run GraphQL and Express in one Node instance",
		link: "run-graphql-and-express",
		notionPage: "0e6becfb9fb64c6b96f4ef66742ac3e9",
		created: 1639982633,
		thumbnail: "/tutorials/graphql-express.png",
		subTitle:
			"Easily run two separate backend apis in the same shared code base",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "How to catch javascript errors by type",
		link: "try-catch-by-type",
		notionPage: "898854cc62d84573807f8da823304ea0",
		created: 1639982632,
		thumbnail: "/tutorials/try-catch.png",
		subTitle:
			"Handle showing an error to your backend or UI via a simple try/catch",
		topic: Topic.Programming,
		languages: [Languages.Typescript],
		tags: [Tags.CodeBlock],
	},
	{
		title: "RESTful API design",
		link: "restful-api-design",
		notionPage: "77d91ff0c0274cb7aeeb3491221b8952",
		created: 1639982532,
		thumbnail: "/tutorials/rest-api.png",
		subTitle:
			"Basic REST API concepts, including resource design, HTTP Codes, Headers etc",
		topic: Topic.Programming,
		languages: [],
		tags: [Tags.Essay],
	},
	{
		title: "Estimation and common pitfalls",
		link: "estimation-and-pitfalls",
		notionPage: "9835c35bb3e34d86b890d90fbb5c2599",
		created: 1639982531,
		thumbnail: "/tutorials/estimation-pitfalls.png",
		subTitle:
			"A discussion on the realities of estimation and common pitfalls teams may find themselves in",
		topic: Topic.Agile,
		languages: [],
		tags: [Tags.Essay],
	},
	{
		title: "Core React JS concepts",
		link: "core-react-concepts",
		notionPage: "6b07a4eeb9e44def926307fa42a38a66",
		created: 1639982520,
		thumbnail: "/tutorials/react-quickstart.png",
		subTitle:
			"Explanation and usage of foundational React topics such as props, hooks, routes, forms etc",
		topic: Topic.Programming,
		languages: [Languages.Javascript, Languages.Typescript],
		tags: [Tags.Essay],
	},
	{
		title: "Rebuilding communication infrastructure in Nepal",
		link: "rebuilding-infrastructure-in-nepal",
		notionPage: "99cbe33175e34a5189dec42c9b95e3e5",
		created: 1639982519,
		thumbnail: "/tutorials/nepal.png",
		subTitle:
			"My experience working in Nepal, rebuilding copper networks after the 2015 earthquakes",
		topic: Topic.Article,
		languages: [],
		tags: [Tags.Essay],
	},
];
