import { Dialog, DialogTitle, Divider, Grid } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { MultiSelectFilter } from "../../src/global/forms/MultiSelectFilterField";
import { SingleSelectFilterField } from "../../src/global/forms/SingleSelectFilterField";
import { PageContainer } from "../../src/global/PageContainer";
import { FilterButton } from "../../src/tutorials/components/buttons/FilterButton";
import { SortButton } from "../../src/tutorials/components/buttons/SortButton";
import { TutorialCard } from "../../src/tutorials/components/cards/TutorialCard";
import { filterMetaData } from "../../src/tutorials/components/filters/filterMetaData";
import { sortMetaData } from "../../src/tutorials/components/filters/sortMetaData";
import {
  availableLanguages,
  availableTags,
  availableTopics,
  getTutorialMetaData
} from "../../src/tutorials/tutorialDataService";
import { Languages, SortOptions, Tags, Topic } from "../../src/tutorials/types";
import { slideTransition } from "../../utils/muiSpecificLogic";
import useDeviceDetect from "../../utils/useDeviceDetect";

const Transition = slideTransition("right");

const Tutorials: NextPage = () => {
  const { isMobile } = useDeviceDetect();
  const tutorialMetaData = getTutorialMetaData();
  const tutorialPurple = "#ce93d8";
  const [showFilterMenu, setShowFilterMenu] = React.useState(false);

  const [sortMetaDataBy, setSortMetaDataBy] = useState(SortOptions.Newest);
  const [sortedMetaData, setSortedMetaData] = useState(tutorialMetaData);

  const [topicFilter, setTopicFilter] = useState<Topic | undefined>(undefined);
  const [languagesFilter, setFilteredLanguages] = useState([] as Languages[]);
  const [tagsFilter, setTagsFilter] = useState([] as Tags[]);

  const [filteredMetaData, setFilteredData] = useState(sortedMetaData);

  useEffect(() => {
    sortMetaData(tutorialMetaData, sortMetaDataBy, setSortedMetaData);
  }, [sortMetaDataBy, filteredMetaData]);

  useEffect(() => {
    filterMetaData(
      sortedMetaData,
      topicFilter,
      languagesFilter,
      tagsFilter,
      setFilteredData
    );
  }, [
    languagesFilter,
    sortedMetaData,
    tagsFilter,
    topicFilter,
    sortMetaDataBy,
  ]);
  const handleCloseFilterMenu = () => {
    setShowFilterMenu(false);
  };

  const filterPopUp = (): JSX.Element => {
    return (
      <Dialog
        open={showFilterMenu}
        TransitionComponent={Transition}
        keepMounted
        onClose={handleCloseFilterMenu}
      >
        <div
          style={
            isMobile
              ? { margin: "10px 0px 50px 0px" }
              : { margin: "20px 50px 50px 50px" }
          }
        >
          <DialogTitle>{"Filter"}</DialogTitle>

          <Divider sx={{ borderColor: tutorialPurple }} />
          <SingleSelectFilterField
            label={"Topic"}
            defaultValue={"All"}
            filter={topicFilter}
            setFilter={setTopicFilter}
            dropDownData={availableTopics}
            highlightColor={tutorialPurple}
          />
          <MultiSelectFilter
            label={"Languages"}
            filter={languagesFilter}
            setFilter={setFilteredLanguages}
            dropDownData={availableLanguages}
            highlightColor={tutorialPurple}
          />
          <MultiSelectFilter
            label={"Tags"}
            filter={tagsFilter}
            setFilter={setTagsFilter}
            dropDownData={availableTags}
            highlightColor={tutorialPurple}
          />
        </div>
      </Dialog>
    );
  };

  return (
    <div>
      <Head>
        <title>Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <div style={{ display: "flex", margin: "10px 30px", gap: "15px" }}>
          <SortButton setSortMetaDataBy={setSortMetaDataBy} />
          <FilterButton setShowFilterMenu={setShowFilterMenu} />
        </div>

        <Grid container spacing={3} justifyContent="center">
          {filteredMetaData.map((dataItem) => (
            <Grid item key={dataItem.title}>
              <TutorialCard cardData={dataItem} accentColor={tutorialPurple} />
            </Grid>
          ))}
        </Grid>

        {filterPopUp()}
      </PageContainer>
    </div>
  );
};

export default Tutorials;
