import { Button, Link } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

const Tutorials: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Tutorials page</h1>
      <Link
        href={`/tutorials/programming/quickly-setup-next-js-with-typescript`}
      >
        <a>Quickly Setup NextJs</a>
      </Link>
    </div>
  );
};

export default Tutorials;
